apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-smtp4dev.fullname" . }}
  labels:
    {{- include "helm-smtp4dev.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.smtp4dev.RelayOptions__SmtpPort | default 25 }}
      targetPort: smtp
      protocol: TCP
      name: smtp
    - port: {{ .Values.smtp4dev.ServerOptions__ImapPort | default 143 }}
      targetPort: imap
      protocol: TCP
      name: imap
  selector:
    {{- include "helm-smtp4dev.selectorLabels" . | nindent 4 }}
